### ISSUE TITLE
lefthand Input should be query text

### ISSUE THREAD

**Issue by MarcusSorealheis** [viewcrunch/OpenTranslation#1]
Right hand displayed should projected in the query and be based on what language is selected:

```javascript
var query = translations.greetings.aggregate([
  {
    $search: {
      text: {
        query: "good morning",
        path: "english"
      }
    }
  },
  {
    $project: {
      french: 1
    }
  }
])
```

**Comment by MarcusSorealheis** [comment]
the value of `query` should be the input text.

the value of `path1` should be the selected language on the left.

the single key of `$project` as above should be the selected language on the right, and the value should always be `1`, as above.

**Comment by viewcrunch** [comment]
@MarcusSorealheis  I'll fix that today Sir

**Comment by viewcrunch** [comment]
Right hand is now projected in the query, based on what language is selected
